# Generated by Django 5.2.5 on 2025-08-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_created_at_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.imagemodel'),
        ),
    ]
